// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create_item.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :one

DO
$$
    BEGIN
        INSERT INTO items (name, description, category_id, group_id, location_id, is_stored, createdAt, updatedAt)
        VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
        RETURNING item_id, createdAt, updatedAt;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Create operation failed for item: %', $1;
            ROLLBACK;
    END
$$
`

type CreateItemRow struct {
}

// noinspection SqlResolveForFile
func (q *Queries) CreateItem(ctx context.Context) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem)
	var i CreateItemRow
	err := row.Scan()
	return i, err
}
