// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_item.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteItem = `-- name: DeleteItem :execresult

DELETE
FROM items
WHERE item_id = $1
RETURNING item_id, name, description, category_id, group_id, location_id, is_stored, "createdAt", "updatedAt"
`

// noinspection SqlResolveForFile
func (q *Queries) DeleteItem(ctx context.Context, itemID int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteItem, itemID)
}
