// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_item.sql

package db

import (
	"context"
)

const deleteItem = `-- name: DeleteItem :exec

DO
$$
    BEGIN
        DELETE
        FROM items
        WHERE item_id = $1
        RETURNING *;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Delete operation failed for item_id: %', $1;
            ROLLBACK;
    END
$$
`

// noinspection SqlResolveForFile
func (q *Queries) DeleteItem(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteItem)
	return err
}
