// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_category.sql

package db

import (
	"context"
)

const getCategory = `-- name: GetCategory :one

SELECT category_id, name, description, "createdAt", "updatedAt"
FROM categories
WHERE category_id = $1
`

// noinspection SqlResolveForFile
func (q *Queries) GetCategory(ctx context.Context, categoryID int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
