// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_location.sql

package db

import (
	"context"
)

const getLocation = `-- name: GetLocation :one

SELECT location_id, tub_id, shelf_id, "createdAt", "updatedAt"
FROM locations
WHERE location_id = $1
`

// noinspection SqlResolveForFile
func (q *Queries) GetLocation(ctx context.Context, locationID int32) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, locationID)
	var i Location
	err := row.Scan(
		&i.LocationID,
		&i.TubID,
		&i.ShelfID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
