// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_group.sql

package db

import (
	"context"
)

const getGroup = `-- name: GetGroup :one

SELECT group_id, name, description, "createdAt", "updatedAt"
FROM groups
WHERE group_id = $1
`

// noinspection SqlResolveForFile
func (q *Queries) GetGroup(ctx context.Context, groupID int32) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, groupID)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
