// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_item.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateItem = `-- name: UpdateItem :execresult

UPDATE items
SET name        = $2,
    description = $3,
    category_id = $4,
    group_id    = $5,
    location_id = $6,
    is_stored   = $7,
	"updatedAt"  = NOW()
WHERE item_id = $1
RETURNING item_id
`

type UpdateItemParams struct {
	ItemID      int32
	Name        string
	Description pgtype.Text
	CategoryID  pgtype.Int4
	GroupID     pgtype.Int4
	LocationID  pgtype.Int4
	IsStored    pgtype.Bool
}

// noinspection SqlResolveForFile
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateItem,
		arg.ItemID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.GroupID,
		arg.LocationID,
		arg.IsStored,
	)
}
