// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_item.sql

package db

import (
	"context"
)

const updateItem = `-- name: UpdateItem :one

DO
$$
    BEGIN
        UPDATE items
        SET name        = $2,
            description = $3,
            category_id = $4,
            group_id    = $5,
            location_id = $6,
            is_stored   = $7,
            updatedAt   = NOW()
        WHERE item_id = $1
        RETURNING item_id, updatedAt;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Update operation failed for item_id: %', $1;
            ROLLBACK;
    END
$$
`

type UpdateItemRow struct {
}

// noinspection SqlResolveForFile
func (q *Queries) UpdateItem(ctx context.Context) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem)
	var i UpdateItemRow
	err := row.Scan()
	return i, err
}
