// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_item.sql

package db

import (
	"context"
)

const getItem = `-- name: GetItem :one

SELECT item_id, name, description, category_id, group_id, location_id, is_stored, "createdAt", "updatedAt"
FROM items
WHERE item_id = $1
`

// noinspection SqlResolveForFile
func (q *Queries) GetItem(ctx context.Context, itemID int32) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, itemID)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.GroupID,
		&i.LocationID,
		&i.IsStored,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
