#file: noinspection SpellCheckingInspection
name: Go Test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4
        
      - name: Check Secrets Availability
        shell: bash
        env: 
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          if [ -z "$DB_PASSWORD" ]; then
            echo "DB_PASSWORD secret is empty"
            exit 1
          else
            echo "DB_PASSWORD secret is set"
          fi

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.2

      - name: Build
        run: go build -v ./...

      - name: Seed database
        run: |
          # Install psql
          sudo apt-get -yqq install postgresql-client
          # Wait for PostgreSQL to become ready
          until PGPASSWORD=${{ env.DB_PASSWORD }} psql -h localhost -U ${{ env.DB_USER }} -c '\q'; do
            sleep 1
          done
          # Seed the database
          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f db/seed_create_db.sql
          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f db/seed_init_db.sql
          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f db/seed_insert.sql

      - name: Run tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
        run: go test ./...
