#file: noinspection SpellCheckingInspection
name: Go Test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      PROJECT_ROOT: ${{ github.workspace }}
      TEST_ENV: true

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: inventory
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.4

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.2

      - name: Build
        run: go build -v ./...

      - name: Seed database
        run: |
          # Install psql
          sudo apt-get -yqq install postgresql-client
          # Wait for PostgreSQL to become ready
          until PGPASSWORD=example psql -h localhost -U postgres -c '\q'; do
            sleep 1
          done
          # Seed the database
          PGPASSWORD=example psql -h localhost -U postgres -d inventory -f db/seed_create_db.sql
          PGPASSWORD=example psql -h localhost -U postgres -d inventory -f db/seed_init_db.sql
          PGPASSWORD=example psql -h localhost -U postgres -d inventory -f db/seed_insert.sql

      - name: Run tests
        env:
          DB_USER: postgres
          DB_PASSWORD: example
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: inventory
          DB_SCHEMA: test_seed
        run: go test ./...
